// Minimal-viable ESLint 9 flat config for the monorepo.
//
// Goals on first land:
//   - Replace the ``echo … && exit 0`` no-ops in apps/web + apps/api so
//     ``pnpm lint`` actually runs ESLint.
//   - Catch the bug classes that bite hardest: no-undef, no-unused-vars
//     (function-arg leniency on, since lots of handlers receive event args
//     they don't use), no-debugger, no-duplicate-case, no-invalid-regexp.
//   - DO NOT drag in eslint-config-next, plugin-react, plugin-jsx-a11y, or
//     typescript-eslint's recommended-type-checked yet — each surfaces 10s
//     to 100s of violations across the existing tree and would need an
//     audit pass per surface to land cleanly. Tracked as a follow-up.
//   - File-glob splits so React components don't trip ``no-undef`` on
//     JSX-globals, and TS-only files use the TS parser.
//
// Local: pnpm lint   (turbo fans out to each workspace; each runs ``eslint .``
// which walks up to find this config).

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

const SHARED_IGNORES = [
  // Build artifacts
  '**/.next/**',
  '**/.turbo/**',
  '**/dist/**',
  '**/build/**',
  '**/out/**',
  '**/.vercel/**',
  '**/coverage/**',
  '**/.venv/**',
  // Generated by Prisma
  '**/prisma/migrations/**',
  // Locale bundles are JSON, not JS
  '**/messages/**',
  // Test snapshots / fixtures with intentionally-weird shapes
  '**/__snapshots__/**',
  // Extension bundles + service worker output
  'apps/extension/dist/**',
  'apps/web/public/sw.js',
  // Editor / OS noise
  '**/node_modules/**',
  // Auto-generated by Next.js — its own triple-slash references are
  // intentional, we can't edit the file.
  'apps/web/next-env.d.ts',
];

export default [
  { ignores: SHARED_IGNORES },

  js.configs.recommended,

  // TypeScript files — parser-aware, but only the non-type-checked rule set.
  // The type-checked variant would need a tsconfig.json wired into the
  // ESLint parserOptions which is per-workspace and expensive on first land.
  ...tseslint.configs.recommended,

  // React hooks plugin — referenced by ``// eslint-disable-next-line
  // react-hooks/exhaustive-deps`` comments scattered through web. Without
  // the plugin, those comments throw "rule definition not found" errors.
  // Use the v5 flat-config shape (plugin + rule wiring).
  {
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  // Globals + per-language tweaks.
  {
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2024,
      },
    },
    rules: {
      // ``_-prefixed`` unused vars are intentional (destructure-rest, JSX-event
      // args we accept-but-ignore). The TS-eslint version supersedes the
      // base no-unused-vars for .ts/.tsx, but we set both so JS files are
      // covered too.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
        },
      ],

      // ``any`` is rampant in adapter code by design (provider response
      // shapes vary). Re-enable when we audit. For now: warn, don't break.
      '@typescript-eslint/no-explicit-any': 'off',

      // ``ts-ignore`` etc. — warn so we see them in PR review without
      // blocking the merge.
      '@typescript-eslint/ban-ts-comment': 'warn',

      // Hard fails — these catch real bugs, not style.
      'no-debugger': 'error',
      'no-duplicate-case': 'error',
      'no-dupe-keys': 'error',
      'no-unreachable': 'error',
    },
  },

  // Test / spec files: lighter rules — fixtures intentionally use
  // ``any``-shaped data, fake providers may shadow real names.
  {
    files: ['**/*.test.{ts,tsx,js,jsx}', '**/*.spec.{ts,tsx,js,jsx}', '**/tests/**', '**/__tests__/**', '**/e2e/**'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  // CommonJS scripts (postinstall hooks, build helpers).
  {
    files: ['**/*.cjs'],
    languageOptions: { sourceType: 'commonjs' },
  },
];
